services:
  postgres:
    container_name: tatamicord-backend
    image: postgres
    environment:
      POSTGRES_DB: tatamicord_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/1.setup.sql