services:
  postgres:
    container_name: tatamicord-backend
    image: postgres
    environment:
      POSTGRES_DB: tatamicord_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/1.setup.sql
      - ./sql/tag_generation.sql:/docker-entrypoint-initdb.d/2.tag_generation.sql
      - ./sql/friend_request_triggers.sql:/docker-entrypoint-initdb.d/3.friend_request_triggers.sql
      - ./sql/test_data.sql:/docker-entrypoint-initdb.d/4.test_data.sql